"""Turn RioModPack/assets/Online.png and OnlinePanel.png into OnlineTexture.h.

    python RioModPack/MakeOnlineTexture.py

The main menu's seven button labels are 156x21 GX C4 textures (4-bit palette
indices, 8x8 tiles) with a 16-entry IA8 palette, all in the ZZZZ.dat container
the menu loads under tag 6 (entry 1740: textures t49 and t52-t57). The Online
label was drawn from those same glyphs, so it fits a 16-entry intensity+alpha
palette exactly and encodes with no loss.

Output layout, the shape "Online Menu.c" expects (two arrays):
  s_onlineTexture   bytes 0 .. 1919   C4 pixels (160x24 after tile padding, 2 px/byte)
                    bytes 1920..1951  TLUT, 16 x IA8 (alpha byte, intensity byte)
  s_onlinePanel     bytes 0 .. 109439 C8 pixels (360x304 after 8x4 tile padding)
                    bytes 109440..    TLUT, 256 x RGB5A3
The panel is the preview picture shown while Online is selected: 357x302, the
same shape and formats as the seven stock pictures (t61-t67 of entry 1740).
assets/OnlinePanel.png was composed from Toy Field's picture by
assets/ComposeOnlinePanel.py (title glyphs borrowed from the other panels).
"""
import os
import struct
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "assets", "Online.png")
PANEL = os.path.join(HERE, "assets", "OnlinePanel.png")
DST = os.path.join(HERE, "OnlineTexture.h")

W, H = 156, 21
PW, PH = 357, 302
PANEL_DATA = 109440
PANEL_TLUT = 512
LABEL_DATA = 1920
LABEL_TLUT = 32


def rgb5a3(c):
    r, g, b, a = c
    if a >= 0xE0:
        return 0x8000 | ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)
    return ((a >> 5) << 12) | ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def colour_counts(px, w, h):
    cols = {}
    for y in range(h):
        for x in range(w):
            c = px[x, y]
            c = (0, 0, 0, 0) if c[3] == 0 else c
            cols[c] = cols.get(c, 0) + 1
    return cols


def encode_panel():
    im = Image.open(PANEL).convert("RGBA")
    if im.size != (PW, PH):
        sys.exit("OnlinePanel.png must be %dx%d" % (PW, PH))
    px = im.load()
    cols = colour_counts(px, PW, PH)
    if len(cols) > 256:
        im = im.quantize(256, method=Image.Quantize.FASTOCTREE).convert("RGBA")
        px = im.load()
        cols = colour_counts(px, PW, PH)
        print("panel quantised to %d colours" % len(cols))
    pal = sorted(cols, key=lambda k: -cols[k])
    idx = {c: i for i, c in enumerate(pal)}
    tlut = b"".join(struct.pack(">H", rgb5a3(c)) for c in pal)
    tlut += bytes(PANEL_TLUT - len(tlut))

    def at(x, y):
        if x >= PW or y >= PH:
            return 0
        c = px[x, y]
        return idx[(0, 0, 0, 0) if c[3] == 0 else c]
    out = bytearray()
    for by in range(0, PH, 4):
        for bx in range(0, PW, 8):
            for yy in range(4):
                for xx in range(8):
                    out.append(at(bx + xx, by + yy))
    assert len(out) == PANEL_DATA, len(out)
    return bytes(out) + tlut, len(pal)


def ia(p):
    r, g, b, a = p
    return ((r * 77 + g * 151 + b * 28) >> 8, a)


def encode_label():
    im = Image.open(SRC).convert("RGBA")
    if im.size != (W, H):
        sys.exit("Online.png must be %dx%d, got %dx%d" % (W, H, im.size[0], im.size[1]))
    px = im.load()
    counts = {}
    for y in range(H):
        for x in range(W):
            k = ia(px[x, y])
            counts[k] = counts.get(k, 0) + 1
    pal = sorted(counts, key=lambda k: -counts[k])
    if len(pal) > 16:
        base = pal[:16]

        def near(k):
            return min(range(16), key=lambda j: (base[j][0] - k[0]) ** 2 + 2 * (base[j][1] - k[1]) ** 2)
        idx = {k: near(k) for k in pal}
        pal = base
        print("warning: %d intensity/alpha pairs, quantised to 16" % len(counts))
    else:
        idx = {k: i for i, k in enumerate(pal)}
    tlut = b"".join(struct.pack(">BB", a, i) for (i, a) in pal)
    tlut += bytes(LABEL_TLUT - len(tlut))

    def at(x, y):
        return idx[ia(px[x, y])] if x < W and y < H else 0
    out = bytearray()
    for by in range(0, H, 8):
        for bx in range(0, W, 8):
            for yy in range(8):
                for xx in range(0, 8, 2):
                    out.append((at(bx + xx, by + yy) << 4) | at(bx + xx + 1, by + yy))
    assert len(out) == LABEL_DATA, len(out)
    return bytes(out) + tlut, len(pal)


def dump(lines, name, blob, per_line):
    lines.append("static const unsigned char %s[%d]" % (name, len(blob)))
    lines.append("    __attribute__((aligned(32))) = {")
    for i in range(0, len(blob), per_line):
        lines.append("    " + ", ".join("0x%02X" % b for b in blob[i:i + per_line]) + ",")
    lines.append("};")


def main():
    label, nlabel = encode_label()
    panel, npanel = encode_panel()
    lines = ["/* GENERATED by RioModPack/MakeOnlineTexture.py from assets/Online.png and",
             " * assets/OnlinePanel.png -- do not edit. Both arrays are 32-byte aligned because",
             " * the GPU reads them in place. */",
             "#define ONLINE_TEX_DATA_SIZE %d" % LABEL_DATA,
             "#define ONLINE_TEX_TLUT_SIZE %d" % LABEL_TLUT,
             "#define ONLINE_PANEL_DATA_SIZE %d" % PANEL_DATA,
             "#define ONLINE_PANEL_TLUT_SIZE %d" % PANEL_TLUT,
             "/* 156x21 GX C4 pixel tiles followed by a 16-entry IA8 TLUT. */"]
    dump(lines, "s_onlineTexture", label, 16)
    lines.append("/* 357x302 GX C8 pixel tiles followed by a 256-entry RGB5A3 TLUT. */")
    dump(lines, "s_onlinePanel", panel, 32)
    with open(DST, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", DST, "(label %d colours, panel %d colours)" % (nlabel, npanel))


if __name__ == "__main__":
    main()
