/*###########################################################
# Balance Patch
###########################################################*/
// Author: PeacockSlayer
// Full change log and the writes that disagree with it: docs/import_balance.md
#include "Include/Rio/StatEdits.h"

static const StatEdit BALANCE_PATCH[] = {
    STAT(CHAR_ID_PEACH, ThrowingArm, 70),
    STAT(CHAR_ID_PEACH, FieldingStatBar, 8),

    ABILITIES_LOW(CHAR_ID_BABYMARIO, FIELDING_ABILITIES_WALL_JUMP | FIELDING_ABILITIES_SLIDING_CATCH),
    STAT(CHAR_ID_BABYMARIO, Speed, 80),
    STAT(CHAR_ID_BABYMARIO, ThrowingArm, 40),
    STAT(CHAR_ID_BABYMARIO, RunningStatBar, 8),

    STAT(CHAR_ID_BABYLUIGI, NonCaptainStarSwing, REGULAR_STAR_SWING_LINEDRIVE),

    STAT(CHAR_ID_WALUIGI, Curve, 100),
    STAT(CHAR_ID_WALUIGI, CaptainStarHitPitch, CAPTAIN_STAR_TYPE_WARIO),

    STAT(CHAR_ID_KOOPA_GREEN, Curve, 70),
    STAT(CHAR_ID_KOOPA_GREEN, ThrowingArm, 60),
    STAT(CHAR_ID_KOOPA_GREEN, PitchingStatBar, 6),

    CHEMISTRY(CHAR_ID_BOO, CHAR_ID_DRYBONES_GRAY, 90),
    CHEMISTRY(CHAR_ID_BOO, CHAR_ID_DRYBONES_GREEN, 90),
    CHEMISTRY(CHAR_ID_BOO, CHAR_ID_DRYBONES_RED, 90),
    CHEMISTRY(CHAR_ID_BOO, CHAR_ID_DRYBONES_BLUE, 90),

    STAT(CHAR_ID_SHYGUY_RED, ChargeHitPower, 70),
    STAT(CHAR_ID_SHYGUY_RED, BattingStatBar, 7),
    CHEMISTRY(CHAR_ID_SHYGUY_RED, CHAR_ID_KINGBOO, 90),

    STAT(CHAR_ID_MONTY, CurveBallSpeed, 140),
    STAT(CHAR_ID_MONTY, FastBallSpeed, 165),
    STAT(CHAR_ID_MONTY, PitchingStatBar, 6),

    STAT(CHAR_ID_BOWSERJR, Speed, 50),
    STAT(CHAR_ID_BOWSERJR, RunningStatBar, 5),

    STAT(CHAR_ID_PARATROOPA_RED, BuntingContactSize, 60),
    STAT(CHAR_ID_PARATROOPA_RED, HitTrajectoryHighLow, 0),

    STAT(CHAR_ID_PIANTA_BLUE, ChargeHitPower, 75),
    STAT(CHAR_ID_PIANTA_BLUE, Speed, 30),
    STAT(CHAR_ID_PIANTA_BLUE, BattingStatBar, 7),
    STAT(CHAR_ID_PIANTA_BLUE, RunningStatBar, 3),

    STAT(CHAR_ID_PIANTA_RED, ChargeHitPower, 80),
    STAT(CHAR_ID_PIANTA_RED, BattingStatBar, 8),

    STAT(CHAR_ID_PIANTA_YELLOW, FastBallSpeed, 190),
    STAT(CHAR_ID_PIANTA_YELLOW, ChargeHitPower, 75),
    STAT(CHAR_ID_PIANTA_YELLOW, BattingStatBar, 7),
    STAT(CHAR_ID_PIANTA_YELLOW, PitchingStatBar, 8),

    ABILITIES_HIGH(CHAR_ID_NOKI_BLUE, FIELDING_ABILITIES_BALL_DASH),

    ABILITIES_HIGH(CHAR_ID_NOKI_RED, FIELDING_ABILITIES_BALL_DASH),

    ABILITIES_LOW(CHAR_ID_TOAD_YELLOW, FIELDING_ABILITIES_MAGICAL_CATCH),

    ABILITIES_HIGH(CHAR_ID_TOAD_GREEN, FIELDING_ABILITIES_SUPER_CATCH | FIELDING_ABILITIES_BODY_CHECK),

    CHEMISTRY(CHAR_ID_KINGBOO, CHAR_ID_SHYGUY_RED, 90),
    CHEMISTRY(CHAR_ID_KINGBOO, CHAR_ID_SHYGUY_BLUE, 90),
    CHEMISTRY(CHAR_ID_KINGBOO, CHAR_ID_SHYGUY_YELLOW, 90),
    CHEMISTRY(CHAR_ID_KINGBOO, CHAR_ID_SHYGUY_GREEN, 90),
    CHEMISTRY(CHAR_ID_KINGBOO, CHAR_ID_SHYGUY_BLACK, 90),

    STAT(CHAR_ID_PARAGOOMBA, Speed, 90),
    STAT(CHAR_ID_PARAGOOMBA, RunningStatBar, 9),

    STAT(CHAR_ID_KOOPA_RED, ChargeHitPower, 85),
    STAT(CHAR_ID_KOOPA_RED, BattingStatBar, 8),

    STAT(CHAR_ID_SHYGUY_BLUE, Speed, 60),
    STAT(CHAR_ID_SHYGUY_BLUE, RunningStatBar, 6),
    CHEMISTRY(CHAR_ID_SHYGUY_BLUE, CHAR_ID_KINGBOO, 90),

    STAT(CHAR_ID_SHYGUY_YELLOW, CaptainStarHitPitch, CAPTAIN_STAR_TYPE_WARIO),
    CHEMISTRY(CHAR_ID_SHYGUY_YELLOW, CHAR_ID_KINGBOO, 90),

    STAT(CHAR_ID_SHYGUY_GREEN, Curve, 70),
    STAT(CHAR_ID_SHYGUY_GREEN, PitchingStatBar, 6),
    CHEMISTRY(CHAR_ID_SHYGUY_GREEN, CHAR_ID_KINGBOO, 90),

    STAT(CHAR_ID_SHYGUY_BLACK, ThrowingArm, 60),
    CHEMISTRY(CHAR_ID_SHYGUY_BLACK, CHAR_ID_KINGBOO, 90),

    ABILITIES_LOW(CHAR_ID_DRYBONES_GRAY, FIELDING_ABILITIES_WALL_SPLAT | FIELDING_ABILITIES_MAGICAL_CATCH),
    CHEMISTRY(CHAR_ID_DRYBONES_GRAY, CHAR_ID_BOO, 90),

    CHEMISTRY(CHAR_ID_DRYBONES_GREEN, CHAR_ID_BOO, 90),

    ABILITIES_LOW(CHAR_ID_DRYBONES_RED, FIELDING_ABILITIES_WALL_SPLAT | FIELDING_ABILITIES_MAGICAL_CATCH),
    STAT(CHAR_ID_DRYBONES_RED, ChargeHitPower, 70),
    STAT(CHAR_ID_DRYBONES_RED, BattingStatBar, 7),
    CHEMISTRY(CHAR_ID_DRYBONES_RED, CHAR_ID_BOO, 90),

    ABILITIES_LOW(CHAR_ID_DRYBONES_BLUE, FIELDING_ABILITIES_WALL_SPLAT | FIELDING_ABILITIES_MAGICAL_CATCH),
    CHEMISTRY(CHAR_ID_DRYBONES_BLUE, CHAR_ID_BOO, 90),
};

CGECKO(BalancePatch,
       .notes = "Buffs the low-tier characters so the whole cast is viable, without nerfing anyone.\n"
                "Adds fielding abilities, raises stats, and gives the Shy Guys and Dry Bones\n"
                "chemistry with King Boo and Boo.");
void BalancePatch(void)
{
    ApplyStatEdits(BALANCE_PATCH, LEN(BALANCE_PATCH));
}
