/*###########################################################
# Balance Patch (April Fools)
###########################################################*/
// Author: PeacockSlayer, LittleCoaks
// Full change log, the Bowser draft hook, and the writes that disagree with the log: docs/import_balance.md
#include "Include/Rio/StatEdits.h"
#include "Include/Rio/CssSquares.h"
#include "Gecko Codes/Balance/SuperJump.h"

static const u8 REMOVED_CHARACTERS[] = {
    CHAR_ID_SHYGUY_RED, CHAR_ID_SHYGUY_BLUE, CHAR_ID_SHYGUY_YELLOW, CHAR_ID_SHYGUY_GREEN, CHAR_ID_SHYGUY_BLACK,
};

static const StatEdit APRIL_FOOLS_PATCH[] = {
    CHEMISTRY(CHAR_ID_MARIO, CHAR_ID_LUIGI, 5),
    CHEMISTRY(CHAR_ID_MARIO, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_LUIGI, CHAR_ID_MARIO, 5),
    CHEMISTRY(CHAR_ID_LUIGI, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_DK, SlapContactSize, 99),
    STAT(CHAR_ID_DK, ChargeContactSize, 99),
    STAT(CHAR_ID_DK, ChargeHitPower, 85),
    CHEMISTRY(CHAR_ID_DK, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_DIDDY, CurveBallSpeed, 50),
    STAT(CHAR_ID_DIDDY, FastBallSpeed, 200),
    STAT(CHAR_ID_DIDDY, Curve, 101),
    CHEMISTRY(CHAR_ID_DIDDY, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_PEACH, HitTrajectoryHighLow, 0),

    CHEMISTRY(CHAR_ID_DAISY, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_YOSHI, CaptainStarHitPitch, CAPTAIN_STAR_TYPE_BIRDO),
    CHEMISTRY(CHAR_ID_YOSHI, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_BABYMARIO, ThrowingArm, 80),
    STAT(CHAR_ID_BABYMARIO, Weight, 9),
    CHEMISTRY(CHAR_ID_BABYMARIO, CHAR_ID_MARIO, 90),
    CHEMISTRY(CHAR_ID_BABYMARIO, CHAR_ID_LUIGI, 90),
    CHEMISTRY(CHAR_ID_BABYMARIO, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_BABYLUIGI, ThrowingArm, 70),
    STAT(CHAR_ID_BABYLUIGI, Weight, 9),
    CHEMISTRY(CHAR_ID_BABYLUIGI, CHAR_ID_MARIO, 90),
    CHEMISTRY(CHAR_ID_BABYLUIGI, CHAR_ID_LUIGI, 90),
    CHEMISTRY(CHAR_ID_BABYLUIGI, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_BOWSER, ChargeHitPower, 99),
    STAT(CHAR_ID_BOWSER, HitTrajectoryPushPull, 2),
    STAT(CHAR_ID_BOWSER, Speed, 40),
    CHEMISTRY(CHAR_ID_BOWSER, CHAR_ID_PEACH, 99),

    ABILITIES_HIGH(CHAR_ID_WARIO, FIELDING_ABILITIES_BALL_DASH | FIELDING_ABILITIES_BODY_CHECK),
    STAT(CHAR_ID_WARIO, HitTrajectoryPushPull, 2),
    STAT(CHAR_ID_WARIO, CaptainStarHitPitch, CAPTAIN_STAR_TYPE_WALUIGI),
    CHEMISTRY(CHAR_ID_WARIO, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_WALUIGI, Curve, 35),
    STAT(CHAR_ID_WALUIGI, CaptainStarHitPitch, CAPTAIN_STAR_TYPE_NONE),
    CHEMISTRY(CHAR_ID_WALUIGI, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_KOOPA_GREEN, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_TOAD_RED, CHAR_ID_PEACH, 99),
    CHEMISTRY(CHAR_ID_TOAD_RED, CHAR_ID_TOAD_BLUE, 90),
    CHEMISTRY(CHAR_ID_TOAD_RED, CHAR_ID_TOAD_YELLOW, 90),
    CHEMISTRY(CHAR_ID_TOAD_RED, CHAR_ID_TOAD_GREEN, 90),
    CHEMISTRY(CHAR_ID_TOAD_RED, CHAR_ID_TOAD_PURPLE, 90),

    STAT(CHAR_ID_BOO, Curve, 100),
    CHEMISTRY(CHAR_ID_BOO, CHAR_ID_DK, 90),
    CHEMISTRY(CHAR_ID_BOO, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_TOADETTE, ThrowingArm, 20),
    CHEMISTRY(CHAR_ID_TOADETTE, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_BIRDO, CaptainStarHitPitch, CAPTAIN_STAR_TYPE_YOSHI),
    CHEMISTRY(CHAR_ID_BIRDO, CHAR_ID_PEACH, 99),

    ABILITIES_HIGH(CHAR_ID_MONTY, FIELDING_ABILITIES_BALL_DASH | FIELDING_ABILITIES_BODY_CHECK | FIELDING_ABILITIES_SUPER_CURVE),
    ABILITIES_LOW(CHAR_ID_MONTY, FIELDING_ABILITIES_LASER | FIELDING_ABILITIES_QUICK_THROW | FIELDING_ABILITIES_SUPER_JUMP),
    CHEMISTRY(CHAR_ID_MONTY, CHAR_ID_PEACH, 99),

    ABILITIES_HIGH(CHAR_ID_BOWSERJR, FIELDING_ABILITIES_BODY_CHECK | FIELDING_ABILITIES_SUPER_CURVE),
    STAT(CHAR_ID_BOWSERJR, SlapHitPower, 56),
    STAT(CHAR_ID_BOWSERJR, Speed, 70),
    CHEMISTRY(CHAR_ID_BOWSERJR, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_PARATROOPA_RED, CHAR_ID_PEACH, 99),

    ABILITIES_LOW(CHAR_ID_PIANTA_BLUE, FIELDING_ABILITIES_SUPER_JUMP),
    STAT(CHAR_ID_PIANTA_BLUE, Speed, 40),
    CHEMISTRY(CHAR_ID_PIANTA_BLUE, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_PIANTA_RED, SlapContactSize, 255),
    STAT(CHAR_ID_PIANTA_RED, ChargeContactSize, 255),
    STAT(CHAR_ID_PIANTA_RED, ChargeHitPower, 99),
    STAT(CHAR_ID_PIANTA_RED, BattingStatBar, 9),
    CHEMISTRY(CHAR_ID_PIANTA_RED, CHAR_ID_MARIO, 90),
    CHEMISTRY(CHAR_ID_PIANTA_RED, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_PIANTA_YELLOW, CurveBallSpeed, 105),
    STAT(CHAR_ID_PIANTA_YELLOW, FastBallSpeed, 205),
    STAT(CHAR_ID_PIANTA_YELLOW, Curve, 205),
    STAT(CHAR_ID_PIANTA_YELLOW, Speed, 30),
    CHEMISTRY(CHAR_ID_PIANTA_YELLOW, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_NOKI_BLUE, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_NOKI_RED, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_NOKI_GREEN, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_BRO_HAMMER, SlapHitPower, 5),
    CHEMISTRY(CHAR_ID_BRO_HAMMER, CHAR_ID_PEACH, 99),

    ABILITIES_LOW(CHAR_ID_TOADSWORTH, FIELDING_ABILITIES_LASER),
    STAT(CHAR_ID_TOADSWORTH, Speed, 80),
    STAT(CHAR_ID_TOADSWORTH, ThrowingArm, 60),
    CHEMISTRY(CHAR_ID_TOADSWORTH, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_TOAD_BLUE, CHAR_ID_PEACH, 99),
    CHEMISTRY(CHAR_ID_TOAD_BLUE, CHAR_ID_TOAD_RED, 90),
    CHEMISTRY(CHAR_ID_TOAD_BLUE, CHAR_ID_TOAD_YELLOW, 90),
    CHEMISTRY(CHAR_ID_TOAD_BLUE, CHAR_ID_TOAD_GREEN, 90),
    CHEMISTRY(CHAR_ID_TOAD_BLUE, CHAR_ID_TOAD_PURPLE, 90),

    CHEMISTRY(CHAR_ID_TOAD_YELLOW, CHAR_ID_PEACH, 99),
    CHEMISTRY(CHAR_ID_TOAD_YELLOW, CHAR_ID_TOAD_RED, 90),
    CHEMISTRY(CHAR_ID_TOAD_YELLOW, CHAR_ID_TOAD_BLUE, 90),
    CHEMISTRY(CHAR_ID_TOAD_YELLOW, CHAR_ID_TOAD_GREEN, 90),
    CHEMISTRY(CHAR_ID_TOAD_YELLOW, CHAR_ID_TOAD_PURPLE, 90),

    CHEMISTRY(CHAR_ID_TOAD_GREEN, CHAR_ID_PEACH, 99),
    CHEMISTRY(CHAR_ID_TOAD_GREEN, CHAR_ID_TOAD_RED, 90),
    CHEMISTRY(CHAR_ID_TOAD_GREEN, CHAR_ID_TOAD_BLUE, 90),
    CHEMISTRY(CHAR_ID_TOAD_GREEN, CHAR_ID_TOAD_YELLOW, 90),
    CHEMISTRY(CHAR_ID_TOAD_GREEN, CHAR_ID_TOAD_PURPLE, 90),

    CHEMISTRY(CHAR_ID_TOAD_PURPLE, CHAR_ID_PEACH, 99),
    CHEMISTRY(CHAR_ID_TOAD_PURPLE, CHAR_ID_TOAD_RED, 90),
    CHEMISTRY(CHAR_ID_TOAD_PURPLE, CHAR_ID_TOAD_BLUE, 90),
    CHEMISTRY(CHAR_ID_TOAD_PURPLE, CHAR_ID_TOAD_YELLOW, 90),
    CHEMISTRY(CHAR_ID_TOAD_PURPLE, CHAR_ID_TOAD_GREEN, 90),

    ABILITIES_LOW(CHAR_ID_MAGIKOOPA_BLUE, FIELDING_ABILITIES_SUPER_JUMP | FIELDING_ABILITIES_MAGICAL_CATCH),
    CHEMISTRY(CHAR_ID_MAGIKOOPA_BLUE, CHAR_ID_PEACH, 99),

    ABILITIES_LOW(CHAR_ID_MAGIKOOPA_RED, FIELDING_ABILITIES_SUPER_JUMP | FIELDING_ABILITIES_MAGICAL_CATCH),
    CHEMISTRY(CHAR_ID_MAGIKOOPA_RED, CHAR_ID_PEACH, 99),

    ABILITIES_LOW(CHAR_ID_MAGIKOOPA_GREEN, FIELDING_ABILITIES_SUPER_JUMP | FIELDING_ABILITIES_MAGICAL_CATCH),
    CHEMISTRY(CHAR_ID_MAGIKOOPA_GREEN, CHAR_ID_PEACH, 99),

    ABILITIES_LOW(CHAR_ID_MAGIKOOPA_YELLOW, FIELDING_ABILITIES_SUPER_JUMP | FIELDING_ABILITIES_MAGICAL_CATCH),
    CHEMISTRY(CHAR_ID_MAGIKOOPA_YELLOW, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_KINGBOO, Curve, 99),
    CHEMISTRY(CHAR_ID_KINGBOO, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_PETEY, SlapContactSize, 40),
    STAT(CHAR_ID_PETEY, ChargeContactSize, 0),
    STAT(CHAR_ID_PETEY, Speed, 80),
    STAT(CHAR_ID_PETEY, RunningStatBar, 8),
    CHEMISTRY(CHAR_ID_PETEY, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_DIXIE, cursedBall, 99),
    STAT(CHAR_ID_DIXIE, curveControl, 99),
    CHEMISTRY(CHAR_ID_DIXIE, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_GOOMBA, ThrowingArm, 5),
    CHEMISTRY(CHAR_ID_GOOMBA, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_PARAGOOMBA, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_KOOPA_RED, BattingStatBar, 9),
    STAT(CHAR_ID_KOOPA_RED, PitchingStatBar, 9),
    STAT(CHAR_ID_KOOPA_RED, RunningStatBar, 9),
    STAT(CHAR_ID_KOOPA_RED, FieldingStatBar, 9),
    CHEMISTRY(CHAR_ID_KOOPA_RED, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_PARATROOPA_GREEN, Curve, 65),
    CHEMISTRY(CHAR_ID_PARATROOPA_GREEN, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_DRYBONES_GRAY, CHAR_ID_PEACH, 99),

    STAT(CHAR_ID_DRYBONES_GREEN, cursedBall, 10),
    CHEMISTRY(CHAR_ID_DRYBONES_GREEN, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_DRYBONES_RED, CHAR_ID_PEACH, 99),

    CHEMISTRY(CHAR_ID_DRYBONES_BLUE, CHAR_ID_PEACH, 99),

    ABILITIES_HIGH(CHAR_ID_BRO_FIRE, FIELDING_ABILITIES_BODY_CHECK | FIELDING_ABILITIES_SUPER_CURVE),
    STAT(CHAR_ID_BRO_FIRE, SlapHitPower, 45),
    CHEMISTRY(CHAR_ID_BRO_FIRE, CHAR_ID_PEACH, 99),

    ABILITIES_HIGH(CHAR_ID_BRO_BOOMERANG, FIELDING_ABILITIES_BODY_CHECK),
    STAT(CHAR_ID_BRO_BOOMERANG, SlapHitPower, 5),
    CHEMISTRY(CHAR_ID_BRO_BOOMERANG, CHAR_ID_PEACH, 99),
};

CGECKO(BalancePatchAprilFools,
       .notes = "A joke balance patch, not meant to be taken seriously.\n"
                "Super jumps go much higher, Bowser can only be picked as a captain, Shy Guy is removed,\n"
                "Peach has chemistry with everyone, and dozens of stats are changed for laughs.");
void BalancePatchAprilFools(void)
{
    ApplyStatEdits(APRIL_FOOLS_PATCH, LEN(APRIL_FOOLS_PATCH));
    FillChemistryRow(CHAR_ID_PEACH, 99);

    for (int i = 0; i < (int)LEN(REMOVED_CHARACTERS); i++)
        Static_Stats_Tables.charOnCharacterGridSelected[REMOVED_CHARACTERS[i]] = 1;

    CssSquareOwner(CSS_SQUARE_SHYGUY) = SQUARE_TAKEN;
}

CGECKO(AprilFoolsSuperDuperJump, .state = MSSB_GAME);
void AprilFoolsSuperDuperJump(void)
{
    SetSuperJumpGravity(SUPER_DUPER_JUMP_GRAVITY);
}

// Same hook as Gecko Codes/Menu/Non-captain Bowser is banned.c; enable only one of the two.
CGECKO(AprilFoolsBanNonCaptainBowser, .address = 0x80051318, .instruction = "li r0, -1");
void AprilFoolsBanNonCaptainBowser(void)
{
    BanFromDraft(CSS_SQUARE_BOWSER, CHAR_ID_BOWSER);
    CssSquareOwner(CSS_SQUARE_BOWSER + 1) = SQUARE_FREE;
}
